name: Engine Health Test

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - 'src/engine/**'
      - '.github/workflows/engine_health_test.yml'

  workflow_dispatch:
    inputs:
      build_preset:
        type: choice
        description: 'Choose the CMake build preset'
        required: false
        default: 'release'
        options:
          - debug
          - release
          - relwithdebinfo
          - minsize

# Ensures only one instance of this workflow is running per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  BUILD_PRESET: ${{ github.event.inputs.build_preset || 'release' }}
  ENGINE_DIR: ${{github.workspace}}/src/engine

jobs:
  build:
    name: Engine Health Test

    # Only runs if the PR status is different to Draft
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
  
    - name: Cache CMake and ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.workflow }}-${{ runner.os }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install ${{env.ENGINE_DIR}}/tools/api-communication/
        pip install ${{env.ENGINE_DIR}}/test/integration_tests/it-utils/
        pip install ${{env.ENGINE_DIR}}/tools/engine-suite/

    - name: Setup VCPKG
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{env.ENGINE_DIR}}/vcpkg'
        vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
        vcpkgJsonGlob: '${{env.ENGINE_DIR}}/vcpkg.json'

    - name: Configure CMake
      run: cmake --preset=${{env.BUILD_PRESET}} --no-warn-unused-cli -S ${{env.ENGINE_DIR}}

    - name: Build
      run: cmake --build ${{env.ENGINE_DIR}}/build --target main -j$(nproc)

    - name: Setup environment
      run: python3 ${{env.ENGINE_DIR}}/test/setupEnvironment.py -e /tmp/actions

    - name: Initial state
      run: python3 ${{env.ENGINE_DIR}}/test/health_test/initialState.py -e /tmp/actions

    - name: Health Test
      run: python3 ${{env.ENGINE_DIR}}/test/health_test/run.py -e /tmp/actions
